In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow.keras.preprocessing.text     import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

2025-06-01 08:19:15.075531: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1748765955.282726      35 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748765955.352134      35 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
with open("/kaggle/input/indian-higher/The Indian higher education system .txt", 'r', 
          encoding='utf-8') as myfile:
    mytext = myfile.read()

In [3]:
mytext

'The Indian higher education system is a vast and intricate network comprising universities, colleges, and institutions spread across the length and breadth of the country. Renowned for its diversity and depth, it caters to millions of students aspiring for academic excellence in various fields.\n\nAt its core, the system is structured around universities, both central and state, which offer a wide range of undergraduate, postgraduate, and doctoral programs. These universities serve as hubs of learning, research, and innovation, providing students with a platform to explore their interests and pursue their passions.\n\nOne of the defining features of the Indian higher education system is its emphasis on specialized disciplines, ranging from engineering, medicine, and science to humanities, social sciences, and commerce. This diversity enables students to choose courses tailored to their career aspirations and academic interests, fostering a culture of multidisciplinary learning and hol

In [4]:
myTokenizer=Tokenizer()
myTokenizer.fit_on_texts([mytext])
total_words=len(myTokenizer.word_index)+1

In [5]:
total_words

205

In [6]:
myTokenizer.word_index

{'and': 1,
 'of': 2,
 'the': 3,
 'to': 4,
 'a': 5,
 'education': 6,
 'system': 7,
 'students': 8,
 'higher': 9,
 'is': 10,
 'indian': 11,
 'universities': 12,
 'institutions': 13,
 'its': 14,
 'learning': 15,
 'their': 16,
 'it': 17,
 'in': 18,
 'as': 19,
 'innovation': 20,
 'for': 21,
 'diversity': 22,
 'academic': 23,
 'excellence': 24,
 'these': 25,
 'research': 26,
 'with': 27,
 'interests': 28,
 'this': 29,
 'aspirations': 30,
 'old': 31,
 'adapt': 32,
 'needs': 33,
 'new': 34,
 'challenges': 35,
 'existing': 36,
 'knowledge': 37,
 'society': 38,
 'vast': 39,
 'intricate': 40,
 'network': 41,
 'comprising': 42,
 'colleges': 43,
 'spread': 44,
 'across': 45,
 'length': 46,
 'breadth': 47,
 'country': 48,
 'renowned': 49,
 'depth': 50,
 'caters': 51,
 'millions': 52,
 'aspiring': 53,
 'various': 54,
 'fields': 55,
 'at': 56,
 'core': 57,
 'structured': 58,
 'around': 59,
 'both': 60,
 'central': 61,
 'state': 62,
 'which': 63,
 'offer': 64,
 'wide': 65,
 'range': 66,
 'undergraduate

In [7]:
my_input_sequences=[]
for line in mytext.split('/n'):
  print(line)
  token_list=myTokenizer.texts_to_sequences([line])[0]
  print(token_list)
  for i in range(1,len(token_list)):
    my_n_gram_sequence=token_list[:i+1]
    my_input_sequences.append(my_n_gram_sequence)

The Indian higher education system is a vast and intricate network comprising universities, colleges, and institutions spread across the length and breadth of the country. Renowned for its diversity and depth, it caters to millions of students aspiring for academic excellence in various fields.

At its core, the system is structured around universities, both central and state, which offer a wide range of undergraduate, postgraduate, and doctoral programs. These universities serve as hubs of learning, research, and innovation, providing students with a platform to explore their interests and pursue their passions.

One of the defining features of the Indian higher education system is its emphasis on specialized disciplines, ranging from engineering, medicine, and science to humanities, social sciences, and commerce. This diversity enables students to choose courses tailored to their career aspirations and academic interests, fostering a culture of multidisciplinary learning and holistic

In [8]:
max_sequence_len=max([len(seq) for seq in my_input_sequences])
input_sequences=np.array(pad_sequences(my_input_sequences,maxlen=max_sequence_len,padding='pre'))

In [9]:
input_sequences[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [10]:
X=input_sequences[:,:-1] 
y=input_sequences[:,-1]

In [11]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [12]:
y[0]

11

In [13]:
y=np.array(tf.keras.utils.to_categorical(y,num_classes=total_words))

In [14]:
y[0] 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [15]:
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words,activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
I0000 00:00:1748765969.650169      35 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13942 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1748765969.651716      35 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13942 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [18]:
model.fit(X,y,epochs=100,verbose=1)

Epoch 1/100


I0000 00:00:1748765973.768974      94 cuda_dnn.cc:529] Loaded cuDNN version 90300


12/12 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - accuracy: 0.0290 - loss: 5.3207
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1002 - loss: 5.1648
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0903 - loss: 4.9347
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0332 - loss: 4.8213  
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0860 - loss: 4.7491
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0941 - loss: 4.7596
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0973 - loss: 4.6981
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0774 - loss: 4.7117
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0792 - loss: 4.7597
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1017 - loss: 4.7657
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0796 - loss: 4.7247
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accurac

In [19]:
input_text = "Indian higher education"
predict_next_words= 10
for _ in range(predict_next_words):
    token_list = myTokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list],
                               maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in myTokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word
print(input_text)

[11, 9, 6]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step
[11, 9, 6, 7]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[11, 9, 6, 7, 10]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[11, 9, 6, 7, 10, 5]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[11, 9, 6, 7, 10, 5, 39]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[11, 9, 6, 7, 10, 5, 39, 1]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[11, 9, 6, 7, 10, 5, 39, 1, 40]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[11, 9, 6, 7, 10, 5, 39, 1, 40, 41]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[11, 9, 6, 7, 10, 5, 39, 1, 40, 41, 42]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[11, 9, 6, 7, 10, 5, 39, 1, 40, 41, 42, 12]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
Indian higher education system is a vast and intricate network comprising universities colleges
